---
title: "tim_practice"
output: html_document
date: "2023-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("readr")
#install.packages("tidyverse")
#install.packages("janitor")
#install.packages("here")
#install.packages("naniar")
#install.packages("shiny")
#install.packages("ggplot2")
#install.packages("RColorBrewer")
#install.packages("paletteer")
#install.packages("ggthemes")
#install.packages("extrafont")
```

```{r}
library(readr)
library(tidyverse)
library(janitor)
library(here)
library(naniar)
library(shiny)
library(ggplot2)
library(RColorBrewer)
library(paletteer)
library(ggthemes)
library(extrafont)
```

```{r}
font_import()
loadfonts(device = "win")
```

```{r}
avocado <- read_csv("avocado-updated-2020 2.csv")
```

```{r}
avocado 
```

```{r}
organic_avocado <- avocado %>% 
                      filter(type == "organic")
```

```{r}
normie_avocado <- avocado %>% 
                      filter(type == "conventional")
```


```{r}
avocado %>% 
  select("year", "geography", "average_price") %>% 
  arrange(desc(average_price))
```

```{r}
organic_avocado %>% 
  arrange((average_price)) %>% 
  ggplot(aes(x=geography, y=average_price, fill=year))+ 
  geom_boxplot(alpha=0.4)+ 
  facet_grid(year~.)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

```

##FINDING THE PRICE EXTREMITIES BY YEAR (ORGANIC)

```{r}
organic_avocado %>%  
  select("year", "geography", "average_price", "date") %>%
  filter(year==2020) %>% 
  arrange(desc(average_price)) %>% 
  slice_max(average_price, n= 3)
```

```{r}
organic_avocado %>%  
  select("year", "geography", "average_price", "date") %>%
  filter(year==2020) %>% 
  arrange(desc(average_price)) %>% 
  slice_min(average_price, n= 3)
```

```{r}
organic_avocado_date <-
  organic_avocado %>% 
    mutate("date" = as.factor(date)) %>% 
    mutate("Geography" = geography)
```


```{r}
#PRICE EXTREMITIES FOR 2015

organic_avocado_date %>% 
  select("year", "Geography", "average_price", "date") %>%
  filter(year==2015) %>% 
  filter(average_price <= 0.87 | average_price >= 2.77) %>% 
  arrange(desc(average_price)) %>% 
  ggplot(aes(x = reorder(date, +average_price),
             y=average_price, 
             fill= Geography, 
             label=average_price)) +
  
      geom_col(position = "dodge", alpha = 0.5, color = "black") +
      scale_fill_brewer(palette = "Greens") +
      geom_label(fill = "palegreen2") +
      theme_grey(base_size = 14) +
      theme(legend.background = element_rect(fill="lightgrey",
                                size=0.5, linetype="solid", 
                                colour ="black")) +
      labs(title="Organic Avocado Price Extremities in 2015",
           x= "Date of Observation",
           y = "Average Price") +
      theme(text=element_text(size=13, family="Comic Sans MS"),
            axis.text.x = element_text(angle = 60, hjust=1))
   
```

```{r}
#PRICE EXTREMITIES FOR 2016
organic_avocado_date %>% 
  select("year", "Geography", "average_price", "date") %>%
  filter(year==2016) %>% 
  filter(average_price <= 0.66 | average_price >= 3.03) %>% 
  arrange(desc(average_price)) %>% 
  ggplot(aes(x = reorder(date, +average_price),
             y=average_price, 
             fill= Geography, 
             label=average_price)) +
  
      geom_col(position = "dodge", alpha = 0.5, color = "black") +
      scale_fill_brewer(palette = "Greens") +
      geom_label(fill = "palegreen2") +
      theme_grey(base_size = 14) +
      theme(legend.background = element_rect(fill="lightgrey",
                                size=0.5, linetype="solid", 
                                colour ="black")) +
      labs(title=" Organic Avocado Price Extremities in 2016",
           x= "Date of Observation",
           y = "Average Price") +
      theme(text=element_text(size=13, family="Comic Sans MS"),
            axis.text.x = element_text(angle = 60, hjust=1))

```

```{r}
#PRICE EXTREMITIES FOR 2017
organic_avocado_date %>% 
  select("year", "Geography", "average_price", "date") %>%
  filter(year==2017) %>% 
  filter(average_price <= 0.49 | average_price >= 3.04) %>% 
  arrange(desc(average_price)) %>% 
  ggplot(aes(x = reorder(date, +average_price),
             y=average_price, 
             fill= Geography, 
             label=average_price)) +
  
      geom_col(position = "dodge", alpha = 0.5, color = "black") +
      scale_fill_brewer(palette = "Greens") +
      geom_label(fill = "palegreen2") +
      theme_grey(base_size = 14) +
      theme(legend.background = element_rect(fill="lightgrey",
                                size=0.5, linetype="solid", 
                                colour ="black")) +
      labs(title="Organic Avocado Price Extremities in 2017",
           x= "Date of Observation",
           y = "Average Price") +
      theme(text=element_text(size=13, family="Comic Sans MS"),
            axis.text.x = element_text(angle = 60, hjust=1))
```

```{r}
#PRICE EXTREMITIES FOR 2018
organic_avocado_date %>% 
  select("year", "Geography", "average_price", "date") %>%
  filter(year==2018) %>% 
  filter(average_price <= 0.75 | average_price >= 2.60) %>% 
  arrange(desc(average_price)) %>% 
  ggplot(aes(x = reorder(date, +average_price),
             y=average_price, 
             fill= Geography, 
             label=average_price)) +
  
      geom_col(position = "dodge", alpha = 0.5, color = "black") +
      scale_fill_brewer(palette = "Greens") +
      geom_label(fill = "palegreen2") +
      theme_grey(base_size = 14) +
      theme(legend.background = element_rect(fill="lightgrey",
                                size=0.5, linetype="solid", 
                                colour ="black")) +
      labs(title="Organic Avocado Price Extremities in 2018",
           x= "Date of Observation",
           y = "Average Price") +
      theme(text=element_text(size=13, family="Comic Sans MS"),
            axis.text.x = element_text(angle = 60, hjust=1))
```

```{r}
#PRICE EXTREMITIES FOR 2019
organic_avocado_date %>% 
  select("year", "Geography", "average_price", "date") %>%
  filter(year==2019) %>% 
  filter(average_price <= 0.79 | average_price >= 2.72) %>% 
  arrange(desc(average_price)) %>% 
  ggplot(aes(x = reorder(date, +average_price),
             y=average_price, 
             fill= Geography, 
             label=average_price)) +
  
      geom_col(position = "dodge", alpha = 0.5, color = "black") +
      scale_fill_brewer(palette = "Greens") +
      geom_label(fill = "palegreen2") +
      theme_grey(base_size = 14) +
      theme(legend.background = element_rect(fill="lightgrey",
                                size=0.5, linetype="solid", 
                                colour ="black")) +
      labs(title="Organic Avocado Price Extremities in 2019",
           x= "Date of Observation",
           y = "Average Price") +
      theme(text=element_text(size=13, family="Comic Sans MS"),
            axis.text.x = element_text(angle = 60, hjust=1))
```

```{r}
#PRICE EXTREMITIES FOR 2020
organic_avocado_date %>% 
  select("year", "Geography", "average_price", "date") %>%
  filter(year==2020) %>% 
  filter(average_price <= 0.85 | average_price >= 2.28) %>% 
  arrange(desc(average_price)) %>% 
  ggplot(aes(x = reorder(date, +average_price),
             y=average_price, 
             fill= Geography, 
             label=average_price)) +
  
      geom_col(position = "dodge", alpha = 0.5, color = "black") +
      scale_fill_brewer(palette = "Greens") +
      geom_label(fill = "palegreen2") +
      theme_grey(base_size = 14) +
      theme(legend.background = element_rect(fill="lightgrey",
                                size=0.5, linetype="solid", 
                                colour ="black")) +
      labs(title="Organic Avocado Price Extremities in 2020",
           x= "Date of Observation",
           y = "Average Price") +
      theme(text=element_text(size=13, family="Comic Sans MS"),
            axis.text.x = element_text(angle = 60, hjust=1))
```



```{r}
organic_avocado %>% 
  arrange(desc(average_price))                  
```


```{r}
names(avocado)
#4046 = non-organic small/medium Hass Avocados (3-5 oz)  
#4225 = non-organic large Hass Avocados (8-10 oz)
#4770 = non-organic extra large Hass Avocados (10-15 oz)
```

```{r}
avocado %>% 
  filter(geography == "Sacramento", type == "organic") %>% 
  select("date","average_price", "type", "year") %>% 
  ggplot(aes(x = date, y=average_price)) + 
  geom_point()+
  geom_smooth(method=lm, se=FALSE)
```
```{r}
ui <- fluidPage(
    selectInput("x", "Select Fill Variable", choices = c("trophic.guild", "thermoregulation"), 
              selected = "trophic.guild"),
    plotOutput("plot")
   
)

server <- function(input, output) {
  output$plot <- renderPlot({
    ggplot(data=homerange, aes_string(x="locomotion", fill=input$x))+
      geom_bar(position = "dodge", alpha = 0.8, color = "black")+
      labs(x=NULL, y=NULL, fill = "Fill Variable")+
      theme_light(base_size = 18)
  })

}
 

shinyApp(ui, server)
```


